// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: chat_completion/chat_completion.proto

package chat_completion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logid         uint64                 `protobuf:"varint,1,opt,name=logid,proto3" json:"logid,omitempty"`
	Userid        string                 `protobuf:"bytes,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Stage         uint32                 `protobuf:"varint,4,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chat_completion_chat_completion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_completion_chat_completion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chat_completion_chat_completion_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetLogid() uint64 {
	if x != nil {
		return x.Logid
	}
	return 0
}

func (x *ChatMessage) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetStage() uint32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

type QuestionAndAnswerPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentText   string                 `protobuf:"bytes,1,opt,name=contentText,proto3" json:"contentText,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionAndAnswerPair) Reset() {
	*x = QuestionAndAnswerPair{}
	mi := &file_chat_completion_chat_completion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionAndAnswerPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionAndAnswerPair) ProtoMessage() {}

func (x *QuestionAndAnswerPair) ProtoReflect() protoreflect.Message {
	mi := &file_chat_completion_chat_completion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionAndAnswerPair.ProtoReflect.Descriptor instead.
func (*QuestionAndAnswerPair) Descriptor() ([]byte, []int) {
	return file_chat_completion_chat_completion_proto_rawDescGZIP(), []int{1}
}

func (x *QuestionAndAnswerPair) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

func (x *QuestionAndAnswerPair) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type ExamAnswerList struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	AnswerList    []*QuestionAndAnswerPair `protobuf:"bytes,1,rep,name=answerList,proto3" json:"answerList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamAnswerList) Reset() {
	*x = ExamAnswerList{}
	mi := &file_chat_completion_chat_completion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamAnswerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamAnswerList) ProtoMessage() {}

func (x *ExamAnswerList) ProtoReflect() protoreflect.Message {
	mi := &file_chat_completion_chat_completion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamAnswerList.ProtoReflect.Descriptor instead.
func (*ExamAnswerList) Descriptor() ([]byte, []int) {
	return file_chat_completion_chat_completion_proto_rawDescGZIP(), []int{2}
}

func (x *ExamAnswerList) GetAnswerList() []*QuestionAndAnswerPair {
	if x != nil {
		return x.AnswerList
	}
	return nil
}

type QueryExamAnswerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaperIds      []string               `protobuf:"bytes,1,rep,name=paperIds,proto3" json:"paperIds,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryExamAnswerListRequest) Reset() {
	*x = QueryExamAnswerListRequest{}
	mi := &file_chat_completion_chat_completion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryExamAnswerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryExamAnswerListRequest) ProtoMessage() {}

func (x *QueryExamAnswerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_completion_chat_completion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryExamAnswerListRequest.ProtoReflect.Descriptor instead.
func (*QueryExamAnswerListRequest) Descriptor() ([]byte, []int) {
	return file_chat_completion_chat_completion_proto_rawDescGZIP(), []int{3}
}

func (x *QueryExamAnswerListRequest) GetPaperIds() []string {
	if x != nil {
		return x.PaperIds
	}
	return nil
}

func (x *QueryExamAnswerListRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type QueryExamAnswerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data          []*ExamAnswerList      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryExamAnswerListResponse) Reset() {
	*x = QueryExamAnswerListResponse{}
	mi := &file_chat_completion_chat_completion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryExamAnswerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryExamAnswerListResponse) ProtoMessage() {}

func (x *QueryExamAnswerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_completion_chat_completion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryExamAnswerListResponse.ProtoReflect.Descriptor instead.
func (*QueryExamAnswerListResponse) Descriptor() ([]byte, []int) {
	return file_chat_completion_chat_completion_proto_rawDescGZIP(), []int{4}
}

func (x *QueryExamAnswerListResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryExamAnswerListResponse) GetData() []*ExamAnswerList {
	if x != nil {
		return x.Data
	}
	return nil
}

type TalkReport struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	OverallScore     string                      `protobuf:"bytes,1,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	FluencyCoherence *TalkReport_ScoreAndComment `protobuf:"bytes,2,opt,name=fluency_coherence,json=fluencyCoherence,proto3" json:"fluency_coherence,omitempty"`
	Pronunciation    *TalkReport_ScoreAndComment `protobuf:"bytes,3,opt,name=pronunciation,proto3" json:"pronunciation,omitempty"`
	Grammer          *TalkReport_ScoreAndComment `protobuf:"bytes,4,opt,name=grammer,proto3" json:"grammer,omitempty"`
	Vocabulary       *TalkReport_ScoreAndComment `protobuf:"bytes,5,opt,name=vocabulary,proto3" json:"vocabulary,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TalkReport) Reset() {
	*x = TalkReport{}
	mi := &file_chat_completion_chat_completion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalkReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkReport) ProtoMessage() {}

func (x *TalkReport) ProtoReflect() protoreflect.Message {
	mi := &file_chat_completion_chat_completion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkReport.ProtoReflect.Descriptor instead.
func (*TalkReport) Descriptor() ([]byte, []int) {
	return file_chat_completion_chat_completion_proto_rawDescGZIP(), []int{5}
}

func (x *TalkReport) GetOverallScore() string {
	if x != nil {
		return x.OverallScore
	}
	return ""
}

func (x *TalkReport) GetFluencyCoherence() *TalkReport_ScoreAndComment {
	if x != nil {
		return x.FluencyCoherence
	}
	return nil
}

func (x *TalkReport) GetPronunciation() *TalkReport_ScoreAndComment {
	if x != nil {
		return x.Pronunciation
	}
	return nil
}

func (x *TalkReport) GetGrammer() *TalkReport_ScoreAndComment {
	if x != nil {
		return x.Grammer
	}
	return nil
}

func (x *TalkReport) GetVocabulary() *TalkReport_ScoreAndComment {
	if x != nil {
		return x.Vocabulary
	}
	return nil
}

type TalkReport_ScoreAndComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetailedScore string                 `protobuf:"bytes,1,opt,name=detailed_score,json=detailedScore,proto3" json:"detailed_score,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TalkReport_ScoreAndComment) Reset() {
	*x = TalkReport_ScoreAndComment{}
	mi := &file_chat_completion_chat_completion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalkReport_ScoreAndComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkReport_ScoreAndComment) ProtoMessage() {}

func (x *TalkReport_ScoreAndComment) ProtoReflect() protoreflect.Message {
	mi := &file_chat_completion_chat_completion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkReport_ScoreAndComment.ProtoReflect.Descriptor instead.
func (*TalkReport_ScoreAndComment) Descriptor() ([]byte, []int) {
	return file_chat_completion_chat_completion_proto_rawDescGZIP(), []int{5, 0}
}

func (x *TalkReport_ScoreAndComment) GetDetailedScore() string {
	if x != nil {
		return x.DetailedScore
	}
	return ""
}

func (x *TalkReport_ScoreAndComment) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_chat_completion_chat_completion_proto protoreflect.FileDescriptor

const file_chat_completion_chat_completion_proto_rawDesc = "" +
	"\n" +
	"%chat_completion/chat_completion.proto\x12\x0fchat_completion\"k\n" +
	"\vChatMessage\x12\x14\n" +
	"\x05logid\x18\x01 \x01(\x04R\x05logid\x12\x16\n" +
	"\x06userid\x18\x02 \x01(\tR\x06userid\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\rR\x05stage\"Q\n" +
	"\x15QuestionAndAnswerPair\x12 \n" +
	"\vcontentText\x18\x01 \x01(\tR\vcontentText\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\"X\n" +
	"\x0eExamAnswerList\x12F\n" +
	"\n" +
	"answerList\x18\x01 \x03(\v2&.chat_completion.QuestionAndAnswerPairR\n" +
	"answerList\"T\n" +
	"\x1aQueryExamAnswerListRequest\x12\x1a\n" +
	"\bpaperIds\x18\x01 \x03(\tR\bpaperIds\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"j\n" +
	"\x1bQueryExamAnswerListResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x123\n" +
	"\x04data\x18\x02 \x03(\v2\x1f.chat_completion.ExamAnswerListR\x04data\"\xc6\x03\n" +
	"\n" +
	"TalkReport\x12#\n" +
	"\roverall_score\x18\x01 \x01(\tR\foverallScore\x12X\n" +
	"\x11fluency_coherence\x18\x02 \x01(\v2+.chat_completion.TalkReport.ScoreAndCommentR\x10fluencyCoherence\x12Q\n" +
	"\rpronunciation\x18\x03 \x01(\v2+.chat_completion.TalkReport.ScoreAndCommentR\rpronunciation\x12E\n" +
	"\agrammer\x18\x04 \x01(\v2+.chat_completion.TalkReport.ScoreAndCommentR\agrammer\x12K\n" +
	"\n" +
	"vocabulary\x18\x05 \x01(\v2+.chat_completion.TalkReport.ScoreAndCommentR\n" +
	"vocabulary\x1aR\n" +
	"\x0fScoreAndComment\x12%\n" +
	"\x0edetailed_score\x18\x01 \x01(\tR\rdetailedScore\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment2\xfc\x17\n" +
	"\vChatService\x12C\n" +
	"\x03ask\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x00\x12H\n" +
	"\x04chat\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x00(\x010\x01\x12X\n" +
	"\x16write_article_by_title\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12\\\n" +
	"\x1aielts_speaking_p1_generate\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12Z\n" +
	"\x18ielts_speaking_p1_enrich\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12\\\n" +
	"\x1aielts_speaking_p2_generate\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12Z\n" +
	"\x18ielts_speaking_p2_enrich\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12Y\n" +
	"\x17ielts_speaking_p2_score\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12\\\n" +
	"\x1aielts_speaking_p3_generate\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12Z\n" +
	"\x18ielts_speaking_p3_enrich\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12Y\n" +
	"\x17ielts_writing_t1_enrich\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12X\n" +
	"\x16ielts_writing_t1_score\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12[\n" +
	"\x19ielts_writing_t2_generate\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12Y\n" +
	"\x17ielts_writing_t2_enrich\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12X\n" +
	"\x16ielts_writing_t2_score\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12_\n" +
	"\x1dielts_speaking_words_synonyms\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12\\\n" +
	"\x1aielts_speaking_words_usage\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12[\n" +
	"\x19ielts_writing_words_theme\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12^\n" +
	"\x1cielts_writing_words_synonyms\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12a\n" +
	"\x1fielts_writing_words_combination\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12\\\n" +
	"\x1atoefl_speaking_p1_generate\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12Z\n" +
	"\x18toefl_speaking_p1_enrich\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12Y\n" +
	"\x17toefl_speaking_p1_score\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12Y\n" +
	"\x17toefl_writing_p1_enrich\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12X\n" +
	"\x16toefl_writing_p1_score\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12Y\n" +
	"\x17toefl_writing_p2_enrich\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12X\n" +
	"\x16toefl_writing_p2_score\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12Y\n" +
	"\x17toefl_writing_p3_enrich\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12[\n" +
	"\x19toefl_writing_p3_generate\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12J\n" +
	"\bcn_to_en\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12J\n" +
	"\ben_to_cn\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x000\x01\x12W\n" +
	"\x17ielts_speaking_exercise\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x00\x12S\n" +
	"\x13ielts_speaking_exam\x12\x1c.chat_completion.ChatMessage\x1a\x1c.chat_completion.ChatMessage\"\x00\x12X\n" +
	"\x16ielts_talk_report_impl\x12\x1f.chat_completion.ExamAnswerList\x1a\x1b.chat_completion.TalkReport\"\x002\x0f\n" +
	"\rReportServiceB9Z7github.com/pkusunjy/openai-server-proto/chat_completionb\x06proto3"

var (
	file_chat_completion_chat_completion_proto_rawDescOnce sync.Once
	file_chat_completion_chat_completion_proto_rawDescData []byte
)

func file_chat_completion_chat_completion_proto_rawDescGZIP() []byte {
	file_chat_completion_chat_completion_proto_rawDescOnce.Do(func() {
		file_chat_completion_chat_completion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_completion_chat_completion_proto_rawDesc), len(file_chat_completion_chat_completion_proto_rawDesc)))
	})
	return file_chat_completion_chat_completion_proto_rawDescData
}

var file_chat_completion_chat_completion_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chat_completion_chat_completion_proto_goTypes = []any{
	(*ChatMessage)(nil),                 // 0: chat_completion.ChatMessage
	(*QuestionAndAnswerPair)(nil),       // 1: chat_completion.QuestionAndAnswerPair
	(*ExamAnswerList)(nil),              // 2: chat_completion.ExamAnswerList
	(*QueryExamAnswerListRequest)(nil),  // 3: chat_completion.QueryExamAnswerListRequest
	(*QueryExamAnswerListResponse)(nil), // 4: chat_completion.QueryExamAnswerListResponse
	(*TalkReport)(nil),                  // 5: chat_completion.TalkReport
	(*TalkReport_ScoreAndComment)(nil),  // 6: chat_completion.TalkReport.ScoreAndComment
}
var file_chat_completion_chat_completion_proto_depIdxs = []int32{
	1,  // 0: chat_completion.ExamAnswerList.answerList:type_name -> chat_completion.QuestionAndAnswerPair
	2,  // 1: chat_completion.QueryExamAnswerListResponse.data:type_name -> chat_completion.ExamAnswerList
	6,  // 2: chat_completion.TalkReport.fluency_coherence:type_name -> chat_completion.TalkReport.ScoreAndComment
	6,  // 3: chat_completion.TalkReport.pronunciation:type_name -> chat_completion.TalkReport.ScoreAndComment
	6,  // 4: chat_completion.TalkReport.grammer:type_name -> chat_completion.TalkReport.ScoreAndComment
	6,  // 5: chat_completion.TalkReport.vocabulary:type_name -> chat_completion.TalkReport.ScoreAndComment
	0,  // 6: chat_completion.ChatService.ask:input_type -> chat_completion.ChatMessage
	0,  // 7: chat_completion.ChatService.chat:input_type -> chat_completion.ChatMessage
	0,  // 8: chat_completion.ChatService.write_article_by_title:input_type -> chat_completion.ChatMessage
	0,  // 9: chat_completion.ChatService.ielts_speaking_p1_generate:input_type -> chat_completion.ChatMessage
	0,  // 10: chat_completion.ChatService.ielts_speaking_p1_enrich:input_type -> chat_completion.ChatMessage
	0,  // 11: chat_completion.ChatService.ielts_speaking_p2_generate:input_type -> chat_completion.ChatMessage
	0,  // 12: chat_completion.ChatService.ielts_speaking_p2_enrich:input_type -> chat_completion.ChatMessage
	0,  // 13: chat_completion.ChatService.ielts_speaking_p2_score:input_type -> chat_completion.ChatMessage
	0,  // 14: chat_completion.ChatService.ielts_speaking_p3_generate:input_type -> chat_completion.ChatMessage
	0,  // 15: chat_completion.ChatService.ielts_speaking_p3_enrich:input_type -> chat_completion.ChatMessage
	0,  // 16: chat_completion.ChatService.ielts_writing_t1_enrich:input_type -> chat_completion.ChatMessage
	0,  // 17: chat_completion.ChatService.ielts_writing_t1_score:input_type -> chat_completion.ChatMessage
	0,  // 18: chat_completion.ChatService.ielts_writing_t2_generate:input_type -> chat_completion.ChatMessage
	0,  // 19: chat_completion.ChatService.ielts_writing_t2_enrich:input_type -> chat_completion.ChatMessage
	0,  // 20: chat_completion.ChatService.ielts_writing_t2_score:input_type -> chat_completion.ChatMessage
	0,  // 21: chat_completion.ChatService.ielts_speaking_words_synonyms:input_type -> chat_completion.ChatMessage
	0,  // 22: chat_completion.ChatService.ielts_speaking_words_usage:input_type -> chat_completion.ChatMessage
	0,  // 23: chat_completion.ChatService.ielts_writing_words_theme:input_type -> chat_completion.ChatMessage
	0,  // 24: chat_completion.ChatService.ielts_writing_words_synonyms:input_type -> chat_completion.ChatMessage
	0,  // 25: chat_completion.ChatService.ielts_writing_words_combination:input_type -> chat_completion.ChatMessage
	0,  // 26: chat_completion.ChatService.toefl_speaking_p1_generate:input_type -> chat_completion.ChatMessage
	0,  // 27: chat_completion.ChatService.toefl_speaking_p1_enrich:input_type -> chat_completion.ChatMessage
	0,  // 28: chat_completion.ChatService.toefl_speaking_p1_score:input_type -> chat_completion.ChatMessage
	0,  // 29: chat_completion.ChatService.toefl_writing_p1_enrich:input_type -> chat_completion.ChatMessage
	0,  // 30: chat_completion.ChatService.toefl_writing_p1_score:input_type -> chat_completion.ChatMessage
	0,  // 31: chat_completion.ChatService.toefl_writing_p2_enrich:input_type -> chat_completion.ChatMessage
	0,  // 32: chat_completion.ChatService.toefl_writing_p2_score:input_type -> chat_completion.ChatMessage
	0,  // 33: chat_completion.ChatService.toefl_writing_p3_enrich:input_type -> chat_completion.ChatMessage
	0,  // 34: chat_completion.ChatService.toefl_writing_p3_generate:input_type -> chat_completion.ChatMessage
	0,  // 35: chat_completion.ChatService.cn_to_en:input_type -> chat_completion.ChatMessage
	0,  // 36: chat_completion.ChatService.en_to_cn:input_type -> chat_completion.ChatMessage
	0,  // 37: chat_completion.ChatService.ielts_speaking_exercise:input_type -> chat_completion.ChatMessage
	0,  // 38: chat_completion.ChatService.ielts_speaking_exam:input_type -> chat_completion.ChatMessage
	2,  // 39: chat_completion.ChatService.ielts_talk_report_impl:input_type -> chat_completion.ExamAnswerList
	0,  // 40: chat_completion.ChatService.ask:output_type -> chat_completion.ChatMessage
	0,  // 41: chat_completion.ChatService.chat:output_type -> chat_completion.ChatMessage
	0,  // 42: chat_completion.ChatService.write_article_by_title:output_type -> chat_completion.ChatMessage
	0,  // 43: chat_completion.ChatService.ielts_speaking_p1_generate:output_type -> chat_completion.ChatMessage
	0,  // 44: chat_completion.ChatService.ielts_speaking_p1_enrich:output_type -> chat_completion.ChatMessage
	0,  // 45: chat_completion.ChatService.ielts_speaking_p2_generate:output_type -> chat_completion.ChatMessage
	0,  // 46: chat_completion.ChatService.ielts_speaking_p2_enrich:output_type -> chat_completion.ChatMessage
	0,  // 47: chat_completion.ChatService.ielts_speaking_p2_score:output_type -> chat_completion.ChatMessage
	0,  // 48: chat_completion.ChatService.ielts_speaking_p3_generate:output_type -> chat_completion.ChatMessage
	0,  // 49: chat_completion.ChatService.ielts_speaking_p3_enrich:output_type -> chat_completion.ChatMessage
	0,  // 50: chat_completion.ChatService.ielts_writing_t1_enrich:output_type -> chat_completion.ChatMessage
	0,  // 51: chat_completion.ChatService.ielts_writing_t1_score:output_type -> chat_completion.ChatMessage
	0,  // 52: chat_completion.ChatService.ielts_writing_t2_generate:output_type -> chat_completion.ChatMessage
	0,  // 53: chat_completion.ChatService.ielts_writing_t2_enrich:output_type -> chat_completion.ChatMessage
	0,  // 54: chat_completion.ChatService.ielts_writing_t2_score:output_type -> chat_completion.ChatMessage
	0,  // 55: chat_completion.ChatService.ielts_speaking_words_synonyms:output_type -> chat_completion.ChatMessage
	0,  // 56: chat_completion.ChatService.ielts_speaking_words_usage:output_type -> chat_completion.ChatMessage
	0,  // 57: chat_completion.ChatService.ielts_writing_words_theme:output_type -> chat_completion.ChatMessage
	0,  // 58: chat_completion.ChatService.ielts_writing_words_synonyms:output_type -> chat_completion.ChatMessage
	0,  // 59: chat_completion.ChatService.ielts_writing_words_combination:output_type -> chat_completion.ChatMessage
	0,  // 60: chat_completion.ChatService.toefl_speaking_p1_generate:output_type -> chat_completion.ChatMessage
	0,  // 61: chat_completion.ChatService.toefl_speaking_p1_enrich:output_type -> chat_completion.ChatMessage
	0,  // 62: chat_completion.ChatService.toefl_speaking_p1_score:output_type -> chat_completion.ChatMessage
	0,  // 63: chat_completion.ChatService.toefl_writing_p1_enrich:output_type -> chat_completion.ChatMessage
	0,  // 64: chat_completion.ChatService.toefl_writing_p1_score:output_type -> chat_completion.ChatMessage
	0,  // 65: chat_completion.ChatService.toefl_writing_p2_enrich:output_type -> chat_completion.ChatMessage
	0,  // 66: chat_completion.ChatService.toefl_writing_p2_score:output_type -> chat_completion.ChatMessage
	0,  // 67: chat_completion.ChatService.toefl_writing_p3_enrich:output_type -> chat_completion.ChatMessage
	0,  // 68: chat_completion.ChatService.toefl_writing_p3_generate:output_type -> chat_completion.ChatMessage
	0,  // 69: chat_completion.ChatService.cn_to_en:output_type -> chat_completion.ChatMessage
	0,  // 70: chat_completion.ChatService.en_to_cn:output_type -> chat_completion.ChatMessage
	0,  // 71: chat_completion.ChatService.ielts_speaking_exercise:output_type -> chat_completion.ChatMessage
	0,  // 72: chat_completion.ChatService.ielts_speaking_exam:output_type -> chat_completion.ChatMessage
	5,  // 73: chat_completion.ChatService.ielts_talk_report_impl:output_type -> chat_completion.TalkReport
	40, // [40:74] is the sub-list for method output_type
	6,  // [6:40] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_chat_completion_chat_completion_proto_init() }
func file_chat_completion_chat_completion_proto_init() {
	if File_chat_completion_chat_completion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_completion_chat_completion_proto_rawDesc), len(file_chat_completion_chat_completion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_chat_completion_chat_completion_proto_goTypes,
		DependencyIndexes: file_chat_completion_chat_completion_proto_depIdxs,
		MessageInfos:      file_chat_completion_chat_completion_proto_msgTypes,
	}.Build()
	File_chat_completion_chat_completion_proto = out.File
	file_chat_completion_chat_completion_proto_goTypes = nil
	file_chat_completion_chat_completion_proto_depIdxs = nil
}
