// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.1
// source: wx_payment/wx_payment.proto

package wx_payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyUrlDecodedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid               string                                    `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Mchid               string                                    `protobuf:"bytes,2,opt,name=mchid,proto3" json:"mchid,omitempty"`
	OutOrderNo          string                                    `protobuf:"bytes,3,opt,name=out_order_no,json=outOrderNo,proto3" json:"out_order_no,omitempty"`
	ServiceId           string                                    `protobuf:"bytes,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Openid              string                                    `protobuf:"bytes,5,opt,name=openid,proto3" json:"openid,omitempty"`
	State               string                                    `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	StateDescription    string                                    `protobuf:"bytes,7,opt,name=state_description,json=stateDescription,proto3" json:"state_description,omitempty"`
	TotalAmount         int64                                     `protobuf:"varint,8,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	ServiceIntroduction string                                    `protobuf:"bytes,9,opt,name=service_introduction,json=serviceIntroduction,proto3" json:"service_introduction,omitempty"`
	PostPayments        []*NotifyUrlDecodedResponse_PostPayments  `protobuf:"bytes,10,rep,name=post_payments,json=postPayments,proto3" json:"post_payments,omitempty"`
	PostDiscounts       []*NotifyUrlDecodedResponse_PostDiscounts `protobuf:"bytes,11,rep,name=post_discounts,json=postDiscounts,proto3" json:"post_discounts,omitempty"`
	RiskFund            *NotifyUrlDecodedResponse_RiskFund        `protobuf:"bytes,12,opt,name=risk_fund,json=riskFund,proto3" json:"risk_fund,omitempty"`
	TimeRange           *NotifyUrlDecodedResponse_TimeRange       `protobuf:"bytes,13,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Location            *NotifyUrlDecodedResponse_Location        `protobuf:"bytes,14,opt,name=location,proto3" json:"location,omitempty"`
	Attach              string                                    `protobuf:"bytes,15,opt,name=attach,proto3" json:"attach,omitempty"`
	NotifyUrl           string                                    `protobuf:"bytes,16,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	OrderId             string                                    `protobuf:"bytes,17,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *NotifyUrlDecodedResponse) Reset() {
	*x = NotifyUrlDecodedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_payment_wx_payment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyUrlDecodedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyUrlDecodedResponse) ProtoMessage() {}

func (x *NotifyUrlDecodedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wx_payment_wx_payment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyUrlDecodedResponse.ProtoReflect.Descriptor instead.
func (*NotifyUrlDecodedResponse) Descriptor() ([]byte, []int) {
	return file_wx_payment_wx_payment_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyUrlDecodedResponse) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *NotifyUrlDecodedResponse) GetMchid() string {
	if x != nil {
		return x.Mchid
	}
	return ""
}

func (x *NotifyUrlDecodedResponse) GetOutOrderNo() string {
	if x != nil {
		return x.OutOrderNo
	}
	return ""
}

func (x *NotifyUrlDecodedResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *NotifyUrlDecodedResponse) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *NotifyUrlDecodedResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NotifyUrlDecodedResponse) GetStateDescription() string {
	if x != nil {
		return x.StateDescription
	}
	return ""
}

func (x *NotifyUrlDecodedResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *NotifyUrlDecodedResponse) GetServiceIntroduction() string {
	if x != nil {
		return x.ServiceIntroduction
	}
	return ""
}

func (x *NotifyUrlDecodedResponse) GetPostPayments() []*NotifyUrlDecodedResponse_PostPayments {
	if x != nil {
		return x.PostPayments
	}
	return nil
}

func (x *NotifyUrlDecodedResponse) GetPostDiscounts() []*NotifyUrlDecodedResponse_PostDiscounts {
	if x != nil {
		return x.PostDiscounts
	}
	return nil
}

func (x *NotifyUrlDecodedResponse) GetRiskFund() *NotifyUrlDecodedResponse_RiskFund {
	if x != nil {
		return x.RiskFund
	}
	return nil
}

func (x *NotifyUrlDecodedResponse) GetTimeRange() *NotifyUrlDecodedResponse_TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *NotifyUrlDecodedResponse) GetLocation() *NotifyUrlDecodedResponse_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *NotifyUrlDecodedResponse) GetAttach() string {
	if x != nil {
		return x.Attach
	}
	return ""
}

func (x *NotifyUrlDecodedResponse) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *NotifyUrlDecodedResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type NotifyUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreateTime   string                              `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	EventType    string                              `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ResourceType string                              `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Resource     *NotifyUrlRequest_NotifyUrlResource `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	Summary      string                              `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *NotifyUrlRequest) Reset() {
	*x = NotifyUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_payment_wx_payment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyUrlRequest) ProtoMessage() {}

func (x *NotifyUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wx_payment_wx_payment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyUrlRequest.ProtoReflect.Descriptor instead.
func (*NotifyUrlRequest) Descriptor() ([]byte, []int) {
	return file_wx_payment_wx_payment_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyUrlRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotifyUrlRequest) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *NotifyUrlRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *NotifyUrlRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *NotifyUrlRequest) GetResource() *NotifyUrlRequest_NotifyUrlResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *NotifyUrlRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type NotifyUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotifyUrlResponse) Reset() {
	*x = NotifyUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_payment_wx_payment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyUrlResponse) ProtoMessage() {}

func (x *NotifyUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wx_payment_wx_payment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyUrlResponse.ProtoReflect.Descriptor instead.
func (*NotifyUrlResponse) Descriptor() ([]byte, []int) {
	return file_wx_payment_wx_payment_proto_rawDescGZIP(), []int{2}
}

type JsApiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Openid string `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
}

func (x *JsApiRequest) Reset() {
	*x = JsApiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_payment_wx_payment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsApiRequest) ProtoMessage() {}

func (x *JsApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wx_payment_wx_payment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsApiRequest.ProtoReflect.Descriptor instead.
func (*JsApiRequest) Descriptor() ([]byte, []int) {
	return file_wx_payment_wx_payment_proto_rawDescGZIP(), []int{3}
}

func (x *JsApiRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

type JsApiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NonceStr  string `protobuf:"bytes,2,opt,name=nonce_str,json=nonceStr,proto3" json:"nonce_str,omitempty"`
	Package   string `protobuf:"bytes,3,opt,name=package,proto3" json:"package,omitempty"`
	SignType  string `protobuf:"bytes,4,opt,name=sign_type,json=signType,proto3" json:"sign_type,omitempty"`
	PaySign   string `protobuf:"bytes,5,opt,name=pay_sign,json=paySign,proto3" json:"pay_sign,omitempty"`
}

func (x *JsApiResponse) Reset() {
	*x = JsApiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_payment_wx_payment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsApiResponse) ProtoMessage() {}

func (x *JsApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wx_payment_wx_payment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsApiResponse.ProtoReflect.Descriptor instead.
func (*JsApiResponse) Descriptor() ([]byte, []int) {
	return file_wx_payment_wx_payment_proto_rawDescGZIP(), []int{4}
}

func (x *JsApiResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *JsApiResponse) GetNonceStr() string {
	if x != nil {
		return x.NonceStr
	}
	return ""
}

func (x *JsApiResponse) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *JsApiResponse) GetSignType() string {
	if x != nil {
		return x.SignType
	}
	return ""
}

func (x *JsApiResponse) GetPaySign() string {
	if x != nil {
		return x.PaySign
	}
	return ""
}

type NotifyUrlDecodedResponse_PostPayments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount      int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Count       int32  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *NotifyUrlDecodedResponse_PostPayments) Reset() {
	*x = NotifyUrlDecodedResponse_PostPayments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_payment_wx_payment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyUrlDecodedResponse_PostPayments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyUrlDecodedResponse_PostPayments) ProtoMessage() {}

func (x *NotifyUrlDecodedResponse_PostPayments) ProtoReflect() protoreflect.Message {
	mi := &file_wx_payment_wx_payment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyUrlDecodedResponse_PostPayments.ProtoReflect.Descriptor instead.
func (*NotifyUrlDecodedResponse_PostPayments) Descriptor() ([]byte, []int) {
	return file_wx_payment_wx_payment_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NotifyUrlDecodedResponse_PostPayments) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotifyUrlDecodedResponse_PostPayments) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NotifyUrlDecodedResponse_PostPayments) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NotifyUrlDecodedResponse_PostPayments) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type NotifyUrlDecodedResponse_PostDiscounts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Amount      int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *NotifyUrlDecodedResponse_PostDiscounts) Reset() {
	*x = NotifyUrlDecodedResponse_PostDiscounts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_payment_wx_payment_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyUrlDecodedResponse_PostDiscounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyUrlDecodedResponse_PostDiscounts) ProtoMessage() {}

func (x *NotifyUrlDecodedResponse_PostDiscounts) ProtoReflect() protoreflect.Message {
	mi := &file_wx_payment_wx_payment_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyUrlDecodedResponse_PostDiscounts.ProtoReflect.Descriptor instead.
func (*NotifyUrlDecodedResponse_PostDiscounts) Descriptor() ([]byte, []int) {
	return file_wx_payment_wx_payment_proto_rawDescGZIP(), []int{0, 1}
}

func (x *NotifyUrlDecodedResponse_PostDiscounts) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotifyUrlDecodedResponse_PostDiscounts) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NotifyUrlDecodedResponse_PostDiscounts) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type NotifyUrlDecodedResponse_RiskFund struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount      int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *NotifyUrlDecodedResponse_RiskFund) Reset() {
	*x = NotifyUrlDecodedResponse_RiskFund{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_payment_wx_payment_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyUrlDecodedResponse_RiskFund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyUrlDecodedResponse_RiskFund) ProtoMessage() {}

func (x *NotifyUrlDecodedResponse_RiskFund) ProtoReflect() protoreflect.Message {
	mi := &file_wx_payment_wx_payment_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyUrlDecodedResponse_RiskFund.ProtoReflect.Descriptor instead.
func (*NotifyUrlDecodedResponse_RiskFund) Descriptor() ([]byte, []int) {
	return file_wx_payment_wx_payment_proto_rawDescGZIP(), []int{0, 2}
}

func (x *NotifyUrlDecodedResponse_RiskFund) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotifyUrlDecodedResponse_RiskFund) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NotifyUrlDecodedResponse_RiskFund) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type NotifyUrlDecodedResponse_TimeRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime       string `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	StartTimeRemark string `protobuf:"bytes,2,opt,name=start_time_remark,json=startTimeRemark,proto3" json:"start_time_remark,omitempty"`
	EndTime         string `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	EndTimeRemark   string `protobuf:"bytes,4,opt,name=end_time_remark,json=endTimeRemark,proto3" json:"end_time_remark,omitempty"`
}

func (x *NotifyUrlDecodedResponse_TimeRange) Reset() {
	*x = NotifyUrlDecodedResponse_TimeRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_payment_wx_payment_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyUrlDecodedResponse_TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyUrlDecodedResponse_TimeRange) ProtoMessage() {}

func (x *NotifyUrlDecodedResponse_TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_wx_payment_wx_payment_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyUrlDecodedResponse_TimeRange.ProtoReflect.Descriptor instead.
func (*NotifyUrlDecodedResponse_TimeRange) Descriptor() ([]byte, []int) {
	return file_wx_payment_wx_payment_proto_rawDescGZIP(), []int{0, 3}
}

func (x *NotifyUrlDecodedResponse_TimeRange) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *NotifyUrlDecodedResponse_TimeRange) GetStartTimeRemark() string {
	if x != nil {
		return x.StartTimeRemark
	}
	return ""
}

func (x *NotifyUrlDecodedResponse_TimeRange) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *NotifyUrlDecodedResponse_TimeRange) GetEndTimeRemark() string {
	if x != nil {
		return x.EndTimeRemark
	}
	return ""
}

type NotifyUrlDecodedResponse_Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartLocation string `protobuf:"bytes,1,opt,name=start_location,json=startLocation,proto3" json:"start_location,omitempty"`
	EndLocation   string `protobuf:"bytes,2,opt,name=end_location,json=endLocation,proto3" json:"end_location,omitempty"`
}

func (x *NotifyUrlDecodedResponse_Location) Reset() {
	*x = NotifyUrlDecodedResponse_Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_payment_wx_payment_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyUrlDecodedResponse_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyUrlDecodedResponse_Location) ProtoMessage() {}

func (x *NotifyUrlDecodedResponse_Location) ProtoReflect() protoreflect.Message {
	mi := &file_wx_payment_wx_payment_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyUrlDecodedResponse_Location.ProtoReflect.Descriptor instead.
func (*NotifyUrlDecodedResponse_Location) Descriptor() ([]byte, []int) {
	return file_wx_payment_wx_payment_proto_rawDescGZIP(), []int{0, 4}
}

func (x *NotifyUrlDecodedResponse_Location) GetStartLocation() string {
	if x != nil {
		return x.StartLocation
	}
	return ""
}

func (x *NotifyUrlDecodedResponse_Location) GetEndLocation() string {
	if x != nil {
		return x.EndLocation
	}
	return ""
}

type NotifyUrlRequest_NotifyUrlResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Algorithm      string `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Ciphertext     string `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	AssociatedData string `protobuf:"bytes,3,opt,name=associated_data,json=associatedData,proto3" json:"associated_data,omitempty"`
	Nonce          string `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *NotifyUrlRequest_NotifyUrlResource) Reset() {
	*x = NotifyUrlRequest_NotifyUrlResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wx_payment_wx_payment_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyUrlRequest_NotifyUrlResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyUrlRequest_NotifyUrlResource) ProtoMessage() {}

func (x *NotifyUrlRequest_NotifyUrlResource) ProtoReflect() protoreflect.Message {
	mi := &file_wx_payment_wx_payment_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyUrlRequest_NotifyUrlResource.ProtoReflect.Descriptor instead.
func (*NotifyUrlRequest_NotifyUrlResource) Descriptor() ([]byte, []int) {
	return file_wx_payment_wx_payment_proto_rawDescGZIP(), []int{1, 0}
}

func (x *NotifyUrlRequest_NotifyUrlResource) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *NotifyUrlRequest_NotifyUrlResource) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

func (x *NotifyUrlRequest_NotifyUrlResource) GetAssociatedData() string {
	if x != nil {
		return x.AssociatedData
	}
	return ""
}

func (x *NotifyUrlRequest_NotifyUrlResource) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

var File_wx_payment_wx_payment_proto protoreflect.FileDescriptor

var file_wx_payment_wx_payment_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x77, 0x78, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x77, 0x78, 0x5f,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x77,
	0x78, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xc2, 0x0a, 0x0a, 0x18, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x63, 0x68, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x63, 0x68,
	0x69, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6f, 0x75, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x75, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4e, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21,
	0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x31, 0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x74,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x56, 0x0a, 0x0d, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x77, 0x78,
	0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55,
	0x72, 0x6c, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x0c,
	0x70, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x59, 0x0a, 0x0e,
	0x70, 0x6f, 0x73, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x0b,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x77, 0x78, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c, 0x44, 0x65, 0x63, 0x6f, 0x64,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x0d, 0x70, 0x6f, 0x73, 0x74, 0x44, 0x69,
	0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x4a, 0x0a, 0x09, 0x72, 0x69, 0x73, 0x6b, 0x5f,
	0x66, 0x75, 0x6e, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x77, 0x78, 0x5f,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72,
	0x6c, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x52, 0x69, 0x73, 0x6b, 0x46, 0x75, 0x6e, 0x64, 0x52, 0x08, 0x72, 0x69, 0x73, 0x6b, 0x46,
	0x75, 0x6e, 0x64, 0x12, 0x4d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x77, 0x78, 0x5f, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c, 0x44, 0x65,
	0x63, 0x6f, 0x64, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x49, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x77, 0x78, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c, 0x44, 0x65, 0x63, 0x6f, 0x64,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x55, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x1a,
	0x72, 0x0a, 0x0c, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x1a, 0x5d, 0x0a, 0x0d, 0x50, 0x6f, 0x73, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x1a, 0x58, 0x0a, 0x08, 0x52, 0x69, 0x73, 0x6b, 0x46, 0x75, 0x6e, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x99, 0x01, 0x0a,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52,
	0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0f, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x1a, 0x54, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x65,
	0x6e, 0x64, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x80,
	0x03, 0x0a, 0x10, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x77, 0x78, 0x5f,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55,
	0x72, 0x6c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x1a, 0x90,
	0x01, 0x0a, 0x11, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74,
	0x68, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x73, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x22, 0x13, 0x0a, 0x11, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x0c, 0x4a, 0x73, 0x41, 0x70, 0x69, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x22, 0x9c,
	0x01, 0x0a, 0x0d, 0x4a, 0x73, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1b,
	0x0a, 0x09, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x69, 0x67, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x32, 0x62, 0x0a,
	0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51,
	0x0a, 0x10, 0x6a, 0x73, 0x61, 0x70, 0x69, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x75,
	0x72, 0x6c, 0x12, 0x1c, 0x2e, 0x77, 0x78, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x77, 0x78, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x32, 0x52, 0x0a, 0x10, 0x57, 0x78, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x6a, 0x73, 0x61, 0x70, 0x69, 0x12, 0x18,
	0x2e, 0x77, 0x78, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4a, 0x73, 0x41, 0x70,
	0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x77, 0x78, 0x5f, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4a, 0x73, 0x41, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6b, 0x75, 0x73, 0x75, 0x6e, 0x6a, 0x79, 0x2f, 0x6f, 0x70, 0x65,
	0x6e, 0x61, 0x69, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x77, 0x78, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_wx_payment_wx_payment_proto_rawDescOnce sync.Once
	file_wx_payment_wx_payment_proto_rawDescData = file_wx_payment_wx_payment_proto_rawDesc
)

func file_wx_payment_wx_payment_proto_rawDescGZIP() []byte {
	file_wx_payment_wx_payment_proto_rawDescOnce.Do(func() {
		file_wx_payment_wx_payment_proto_rawDescData = protoimpl.X.CompressGZIP(file_wx_payment_wx_payment_proto_rawDescData)
	})
	return file_wx_payment_wx_payment_proto_rawDescData
}

var file_wx_payment_wx_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_wx_payment_wx_payment_proto_goTypes = []interface{}{
	(*NotifyUrlDecodedResponse)(nil),               // 0: wx_payment.NotifyUrlDecodedResponse
	(*NotifyUrlRequest)(nil),                       // 1: wx_payment.NotifyUrlRequest
	(*NotifyUrlResponse)(nil),                      // 2: wx_payment.NotifyUrlResponse
	(*JsApiRequest)(nil),                           // 3: wx_payment.JsApiRequest
	(*JsApiResponse)(nil),                          // 4: wx_payment.JsApiResponse
	(*NotifyUrlDecodedResponse_PostPayments)(nil),  // 5: wx_payment.NotifyUrlDecodedResponse.PostPayments
	(*NotifyUrlDecodedResponse_PostDiscounts)(nil), // 6: wx_payment.NotifyUrlDecodedResponse.PostDiscounts
	(*NotifyUrlDecodedResponse_RiskFund)(nil),      // 7: wx_payment.NotifyUrlDecodedResponse.RiskFund
	(*NotifyUrlDecodedResponse_TimeRange)(nil),     // 8: wx_payment.NotifyUrlDecodedResponse.TimeRange
	(*NotifyUrlDecodedResponse_Location)(nil),      // 9: wx_payment.NotifyUrlDecodedResponse.Location
	(*NotifyUrlRequest_NotifyUrlResource)(nil),     // 10: wx_payment.NotifyUrlRequest.NotifyUrlResource
}
var file_wx_payment_wx_payment_proto_depIdxs = []int32{
	5,  // 0: wx_payment.NotifyUrlDecodedResponse.post_payments:type_name -> wx_payment.NotifyUrlDecodedResponse.PostPayments
	6,  // 1: wx_payment.NotifyUrlDecodedResponse.post_discounts:type_name -> wx_payment.NotifyUrlDecodedResponse.PostDiscounts
	7,  // 2: wx_payment.NotifyUrlDecodedResponse.risk_fund:type_name -> wx_payment.NotifyUrlDecodedResponse.RiskFund
	8,  // 3: wx_payment.NotifyUrlDecodedResponse.time_range:type_name -> wx_payment.NotifyUrlDecodedResponse.TimeRange
	9,  // 4: wx_payment.NotifyUrlDecodedResponse.location:type_name -> wx_payment.NotifyUrlDecodedResponse.Location
	10, // 5: wx_payment.NotifyUrlRequest.resource:type_name -> wx_payment.NotifyUrlRequest.NotifyUrlResource
	1,  // 6: wx_payment.NotifyService.jsapi_notify_url:input_type -> wx_payment.NotifyUrlRequest
	3,  // 7: wx_payment.WxPaymentService.jsapi:input_type -> wx_payment.JsApiRequest
	2,  // 8: wx_payment.NotifyService.jsapi_notify_url:output_type -> wx_payment.NotifyUrlResponse
	4,  // 9: wx_payment.WxPaymentService.jsapi:output_type -> wx_payment.JsApiResponse
	8,  // [8:10] is the sub-list for method output_type
	6,  // [6:8] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_wx_payment_wx_payment_proto_init() }
func file_wx_payment_wx_payment_proto_init() {
	if File_wx_payment_wx_payment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wx_payment_wx_payment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyUrlDecodedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_payment_wx_payment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_payment_wx_payment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_payment_wx_payment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsApiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_payment_wx_payment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsApiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_payment_wx_payment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyUrlDecodedResponse_PostPayments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_payment_wx_payment_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyUrlDecodedResponse_PostDiscounts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_payment_wx_payment_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyUrlDecodedResponse_RiskFund); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_payment_wx_payment_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyUrlDecodedResponse_TimeRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_payment_wx_payment_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyUrlDecodedResponse_Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wx_payment_wx_payment_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyUrlRequest_NotifyUrlResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wx_payment_wx_payment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_wx_payment_wx_payment_proto_goTypes,
		DependencyIndexes: file_wx_payment_wx_payment_proto_depIdxs,
		MessageInfos:      file_wx_payment_wx_payment_proto_msgTypes,
	}.Build()
	File_wx_payment_wx_payment_proto = out.File
	file_wx_payment_wx_payment_proto_rawDesc = nil
	file_wx_payment_wx_payment_proto_goTypes = nil
	file_wx_payment_wx_payment_proto_depIdxs = nil
}
